name: Daily Quote Cleanup

on:
  schedule:
    - cron: '0 1 * * *'   # Every day at 01:00 UTC, after seeding
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - name: Run quote cleanup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx ts-node src/cleanupQuotes.ts