name: Daily Quote Seeder

on:
  schedule:
    - cron: '0 0 * * *'   # Every day at midnight UTC
  workflow_dispatch:        # Allows manual trigger from Actions tab

jobs:
  run-seeder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run seeder
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: npx ts-node src/seedQuotes.ts